In [2]:
import tensorflow as tf

print(tf.__version__)

2.9.0


In [8]:
scalar = tf.constant(7)
print(scalar.ndim)

vector = tf.constant([1, 2, 3], dtype=tf.float64)
print(vector.ndim)

matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
print(matrix.ndim)

nd_tensor = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(nd_tensor.ndim)

0
1
2
3


Summarize:
* Scalar is a number
* Vector is a number with direction
* matrix is 2 dimension array of numbers
* tensor is an N-dimension array of numbers

In [4]:
changable_tensor = tf.Variable([1,2])
changable_tensor[1].assign(3)
changable_tensor[0].assign(4)

changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 3], dtype=int32)>

In [9]:
random_1 = tf.random.Generator.from_seed(100)
random_1 = random_1.normal([2, 3])
random_2 = tf.random.Generator.from_seed(100)
random_2 = random_2.normal([2, 3])
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.90112925, -0.0175216 , -0.4188493 ],
        [ 0.29532313,  0.08036723, -1.7199678 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205,  0.01063002],
        [ 1.5165398 ,  0.27305737, -0.29925638]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False]])>)

In [26]:
origin = tf.constant([[1, 2],
                      [4, 5],
                      [7, 8],
                      ]) 

shuffled = tf.random.shuffle(origin, seed=100)
shuffled
origin

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [7, 8]], dtype=int32)>

In [59]:
tf.random.set_seed(100)


In [67]:
shuffled2 = tf.random.shuffle(origin,seed=100)

shuffled2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [7, 8],
       [1, 2]], dtype=int32)>

In [69]:
A= tf.ones([2, 3])
B= tf.zeros([3, 2])

A,B

AttributeError: module 'tensorflow' has no attribute 'hunderd_ones'

In [77]:
import numpy as np

npa = np.arange(24)
npb = npa.reshape([3,8])

npa,npb

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]]))

In [79]:
ta = tf.constant(npa)
tb = tf.constant(npa, shape=[2, 3, 4])
size= tf.size(tb)
ta,tb, size

(<tf.Tensor: shape=(24,), dtype=int64, numpy=
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23])>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [89]:
original = tf.constant([[1, 2, 3], [4, 5, 6]])

original[:2,:1]
original[:2,:1], original[0][2]


(<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[1],
        [4]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>)

In [97]:
expand1 = original[..., tf.newaxis]
expand2 = original[tf.newaxis, ...]
expand3 = tf.expand_dims(original, axis=0)
expand4 = tf.expand_dims(original, axis=1)
expand5 = tf.expand_dims(original, axis=2)
expand1, expand2, expand3, expand4, expand5

(<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
 array([[[1],
         [2],
         [3]],
 
        [[4],
         [5],
         [6]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 1, 3), dtype=int32, numpy=
 array([[[1, 2, 3]],
 
        [[4, 5, 6]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
 array([[[1],
         [2],
         [3]],
 
        [[4],
         [5],
         [6]]], dtype=int32)>)

In [101]:

original +10
original *10
tf.multiply(original, 5)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5, 10, 15],
       [20, 25, 30]], dtype=int32)>

In [107]:
origin2 = tf.constant([[1, 2], [4, 5],[7, 8]])
tf.matmul(original, origin2)
original @ origin2


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 36],
       [66, 81]], dtype=int32)>

In [112]:
tf.reshape(original, [3, 2]) @ original
original
original @ tf.transpose(original)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [118]:
tf.tensordot( tf.transpose(original), original, axes=1)
tf.tensordot( original, tf.transpose(original), axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [119]:
original, original.dtype

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 tf.int32)

In [120]:
tf.cast(original, tf.float32)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [122]:
arr = tf.constant(np.random.randint(1,1000,size=20))
arr

<tf.Tensor: shape=(20,), dtype=int64, numpy=
array([770, 326, 672, 976, 909, 821, 971, 318, 258, 491,   4, 739, 349,
        82, 993,   2, 292, 263,  16, 308])>

In [128]:
tf.reduce_min(arr), tf.reduce_mean(arr), tf.reduce_max(arr), tf.reduce_sum(arr)

(<tf.Tensor: shape=(), dtype=int64, numpy=2>,
 <tf.Tensor: shape=(), dtype=int64, numpy=478>,
 <tf.Tensor: shape=(), dtype=int64, numpy=993>,
 <tf.Tensor: shape=(), dtype=int64, numpy=9560>)

In [129]:
farr = tf.cast(arr, tf.float32)
tf.math.reduce_variance(arr), tf.math.reduce_std(arr)

TypeError: Input must be either real or complex. Received integer type <dtype: 'int64'>.