In [2]:
import tensorflow as tf

print(tf.__version__)

2.9.0


In [8]:
scalar = tf.constant(7)
print(scalar.ndim)

vector = tf.constant([1, 2, 3], dtype=tf.float64)
print(vector.ndim)

matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
print(matrix.ndim)

nd_tensor = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(nd_tensor.ndim)

0
1
2
3


Summarize:
* Scalar is a number
* Vector is a number with direction
* matrix is 2 dimension array of numbers
* tensor is an N-dimension array of numbers

In [4]:
changable_tensor = tf.Variable([1,2])
changable_tensor[1].assign(3)
changable_tensor[0].assign(4)

changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 3], dtype=int32)>

In [9]:
random_1 = tf.random.Generator.from_seed(100)
random_1 = random_1.normal([2, 3])
random_2 = tf.random.Generator.from_seed(100)
random_2 = random_2.normal([2, 3])
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.90112925, -0.0175216 , -0.4188493 ],
        [ 0.29532313,  0.08036723, -1.7199678 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205,  0.01063002],
        [ 1.5165398 ,  0.27305737, -0.29925638]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False]])>)

In [26]:
origin = tf.constant([[1, 2],
                      [4, 5],
                      [7, 8],
                      ]) 

shuffled = tf.random.shuffle(origin, seed=100)
shuffled
origin

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [7, 8]], dtype=int32)>

In [59]:
tf.random.set_seed(100)


In [67]:
shuffled2 = tf.random.shuffle(origin,seed=100)

shuffled2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [7, 8],
       [1, 2]], dtype=int32)>